# Generated by Django 4.2.25 on 2025-11-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        ("users", "0001_initial"),
        ("dealerships", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="users.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="dealership_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dealerships.dealership",
            ),
        ),
    ]
