# Generated by Django 4.2.25 on 2025-11-04 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        ("dealerships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealership",
            name="admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_dealership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealership",
            name="preferred_specs",
            field=models.ManyToManyField(
                blank=True,
                related_name="preferred_by_dealerships",
                to="vehicles.carspecification",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealershippreferredsupplier",
            unique_together={("dealership", "car_model")},
        ),
        migrations.AlterUniqueTogether(
            name="dealershipcarinventory",
            unique_together={("dealership", "car_model")},
        ),
    ]
